### ISSUE TITLE
What are the core code lines of StructBERT? Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [alibaba/AliceMind#11]
https://github.com/alibaba/AliceMind/blob/main/StructBERT/modeling.py

**Comment by guotong1988** [comment]
@luofuli ???

**Comment by guotong1988** [comment]
the core innovation code.

**Comment by wangwei7175878** [comment]
> The core innovation code.

The core innovation code is pre-training code which is not released yet. The neural network architecture is as same as BERT. #7

**Comment by guotong1988** [comment]
Thank you.
