### ISSUE TITLE
Could you tell me where is the code implement of cross-attention in the paper VECO?

### ISSUE THREAD

**Issue by GoneZ5** [alibaba/AliceMind#14]
Could you tell me where is the code implement of cross-attention in the paper VECO?

**Comment by luofuli** [comment]
We only released the fine-tuning code of VECO. [In the directory of NLG code](https://github.com/alibaba/AliceMind/tree/main/VECO/NLG) which are implemented based on [fairseq](https://github.com/pytorch/fairseq), we transfer the model state_dict keys into the format of [fairseq](https://github.com/pytorch/fairseq).  
The `encoder_attn` denotes the  `cross_attention`. The detailed mappings are shown as below:

{'cross_attention.self.query.weight': 'encoder_attn.q_proj.weight',
'cross_attention.self.query.bias': 'encoder_attn.q_proj.bias',
'cross_attention.self.key.weight': 'encoder_attn.k_proj.weight',
'cross_attention.self.key.bias': 'encoder_attn.k_proj.bias',
'cross_attention.self.value.weight': 'encoder_attn.v_proj.weight',
'cross_attention.self.value.bias': 'encoder_attn.v_proj.bias',
'cross_attention.output.dense.weight': 'encoder_attn.out_proj.weight',
'cross_attention.output.dense.bias': 'encoder_attn.out_proj.bias',
'cross_attention.output.LayerNorm.gamma': 'encoder_attn_layer_norm.weight',
'cross_attention.output.LayerNorm.beta': 'encoder_attn_layer_norm.bias'}
