### ISSUE TITLE
StructuralLM, 如何定义cell box

### ISSUE THREAD

**Issue by paulpaul91** [alibaba/AliceMind#15]
StructuralLM, 如何定义cell box
对于ocr 通过给出的是一整行信息，或者说key:value 靠的很近，请问这算一个cell吗？还是算两个？

**Comment by lcl6679292** [comment]
我们论文里面也有说过，cell box取决于OCR工具的识别结果，所以你如果key:value 靠的很近，被OCR识别到一个bounding box里面，那么就算一个cell

**Comment by luofuli** [comment]
I close this issue since it has been solved.
