### ISSUE TITLE
Funsd data processing problem? input_mask.append(pad_index)

### ISSUE THREAD

**Issue by Cppowboy** [alibaba/AliceMind#17]
https://github.com/alibaba/AliceMind/blob/main/StructuralLM/run_seq_labeling.py#L386

Why append pad_index to input_mask and segment_ids? This will make the input_mask all 1, and segment_ids begins with 0 and ends with 1.

**Comment by lcl6679292** [comment]
Our model is based on the RoBERTa, and the pad_index corresponds to id 1 in the RoBERTa vocabulary
