### ISSUE TITLE
TNEWS结果

### ISSUE THREAD

**Issue by sunyilgdx** [alibaba/AliceMind#2]
您好，感谢您的工作，有一点小问题，文章中汇报的TNEWS结果为什么跟CLUE原文中汇报的差距这么大，[CLUE原文](https://arxiv.org/abs/2004.05986)汇报的测试接上的Accuracy大概在56-58之间，而在本文中普遍在67-68之间

**Comment by Erutan-pku** [comment]
您好，如果指Lattice-BERT中汇报的结果，因为Lattice-BERT参考AMBERT等工作，对TNEWS做了数据增强：在分类时将keywords信息也合并进去了。详见Lattice-BERT论文（https://arxiv.org/pdf/2104.07204.pdf）Appendix-C 中的 Detailed Implementation。
