### ISSUE TITLE
What’s the CLEVER? 

### ISSUE THREAD

**Issue by Akeepers** [alibaba/AliceMind#29]
I found `StructBERT + CLEVER` in the GLUE benchmark. Is that a technology about the pertaining or fine-tuning? Can you provide more information about `CLEVER`? Thanks a lot.

![image](https://user-images.githubusercontent.com/22610351/146734276-3c848bee-7c60-40ec-a8bb-14d0cd16ef59.png)

**Comment by wangwei7175878** [comment]
CLEVER is a fine-tuning technology. We are working on the paper. Before that, you can directly contact the author for more details by email: liangzhu.glzATalibaba-incDOTcom.

**Comment by Akeepers** [comment]
Thanks~
