### ISSUE TITLE
structralLM copy related work from LayoutLMv2

### ISSUE THREAD

**Issue by paulpaul91** [alibaba/AliceMind#31]
layoutlmv2 related work
![image](https://user-images.githubusercontent.com/22076188/148679569-d900951c-5026-4329-9617-bd613bf9a3ac.png)
structralral related work
![image](https://user-images.githubusercontent.com/22076188/148679573-3eb741ad-c7b8-48fe-af58-5a80c388b0ba.png)

**Comment by paulpaul91** [comment]
Both accepted by ACL2021， who copy who

**Comment by lcl6679292** [comment]
Thank you for your interest in our work. StructuralLM and LayoutLM propose different solutions to the problem of visually-rich document modeling. The StructuralLM approach is original and distinct from LayoutLM in document types, model architectures and research findings. Our StructuralLM paper has properly cited the previous work of LayoutLM(v1), and referred to the baseline models used in the v1 paper, including the name RoBERTa. LayoutLM(v2) later replaced the baseline from RoBERTa to UniLMv2, which led to the discrepancy in the model names. As StructuralLM and LayoutLM both address the same research problem, which is an emerging topic with limited studies in the past, that results in the similarity in citations of the related work sections.
We sincerely appreciate the contribution of LayoutLM to this research field.

**Comment by paulpaul91** [comment]
> Thank you for your interest in our work. StructuralLM and LayoutLM propose different solutions to the problem of visually-rich document modeling. The StructuralLM approach is original and distinct from LayoutLM in document types, model architectures and research findings. Our StructuralLM paper has properly cited the previous work of LayoutLM(v1), and referred to the baseline models used in the v1 paper, including the name RoBERTa. LayoutLM(v2) later replaced the baseline from RoBERTa to UniLMv2, which led to the discrepancy in the model names. As StructuralLM and LayoutLM both address the same research problem, which is an emerging topic with limited studies in the past, that results in the similarity in citations of the related work sections. We sincerely appreciate the contribution of LayoutLM to this research field.

interesting
