### ISSUE TITLE
will you consider push your work to huggingface model hub?

### ISSUE THREAD

**Issue by tangzhy** [alibaba/AliceMind#32]
It's a bit suffering to use your model like StructBert. 

There are some minor code modifications compared with huggingface's bert. 

So i won't say it's safe to directly use huggingface's `from_pretrained` api on your released model checkpoint, while it could be inconvenient to use your modeling code where the BertModel are not inherited with huggingface's `PreTrainedModel`.

Any advice?

**Comment by wangwei7175878** [comment]
Using StructBert in huggingface needs to modify several key names: layer norm gama-> layer norm weight, layer norm beta -> layer norm bias. The rest should remain the same.
