### ISSUE TITLE
fail to download pretrained model and data

### ISSUE THREAD

**Issue by cssddnnc9527** [alibaba/AliceMind#33]
Hi, Author

Thanks for your great contribution.

But I can't download the pretrained model and data whose link starts with 
http://119608.oss-cn-hangzhou-zmf.aliyuncs.com

For example, the links as follows can not be downloaded:
http://119608.oss-cn-hangzhou-zmf.aliyuncs.com/structvbert/pretrained_model.tar.gz
http://119608.oss-cn-hangzhou-zmf.aliyuncs.com/structvbert/data.tar.gz

Any advice is appreciated! Thanks.

**Comment by wangwei7175878** [comment]
Thanks for pointing out, please use the new link to download.
