### ISSUE TITLE
请问在哪能看到这篇论文 Parameter-Efficient Sparsity for Large Language Models Fine-Tuning

### ISSUE THREAD

**Issue by Heyuanhong** [alibaba/AliceMind#38]
请问在哪能看到这篇论文 Parameter-Efficient Sparsity for Large Language Models Fine-Tuning

**Comment by Chuanqi1992** [comment]
Thanks for your attention.
We are preparing the camera-ready version.
You'll find it soon (about 1 to 2 weeks).
