### ISSUE TITLE
请教下XNLI的复现结果？

### ISSUE THREAD

**Issue by zhuchenxi** [alibaba/AliceMind#4]
hello~ 我这边使用train_xnli.sh的默认参数进行了训练，最终得到平均acc为78.63%，和论文中的79.9%的结果有些出入，且看上去应该是每种语言的acc都低了一点。请问下可能是什么原因导致的呢？非常感谢。
我这边是用的单核GPU，采用Tesla M40 24GB卡，Driver Version: 440.64，CUDA Version: 10.2
我从和论文中的fine-tune参数对比上看。
一个是sh代码里面使用的epoch=2，论文中是用的3/5/10选的
另一个是这里TOTAL_BATCH_SIZE=64，BATCH_SIZE=2，论文中是16/32/64选的
会不会是这两个超参导致的出入呢？
非常感谢~

**Comment by hit-computer** [comment]
@zhuchenxi hello！ 以下是我们实验的参数设置：

```sh
LR=2e-5
EPOCH=2
TOTAL_BATCH_SIZE=64
```

实验环境配置是：torch Version：1.3.1；transformers Version: 2.3.0；GPU：Tesla V100 16GB；CUDA Version:10.0.130

实验结果在英语的dev集上通过acc选择最优模型（模型会保存到 checkpoint-best 目录下），然后用该模型对测试集进行预测，以下是我们复现的结果：

```
ar=0.7868263473053893
bg=0.8291417165668663
de=0.8235528942115768
el=0.8191616766467066
en=0.883433133732535
es=0.8471057884231536
fr=0.8297405189620759
hi=0.7606786427145709
ru=0.8011976047904191
sw=0.7351297405189621
th=0.7590818363273453
tr=0.7888223552894211
ur=0.7153692614770459
vi=0.7998003992015968
zh=0.7918163672654691

=====
Avg_lang_acc =0.7980572188955422
```

有问题欢迎随时交流，十分感谢！
