### ISSUE TITLE
SOFA-models

### ISSUE THREAD

**Issue by Wangxh-07** [alibaba/AliceMind#50]
(https://github.com/alibaba/AliceMind/tree/main/SOFA/sofa/models)/__init__.py /
为什么这里只有三个，roberta没有init呢？
同样README.md里面也没有roberta的相关结果，所以roberta暂时还不能实现是么？
那么如果我需要加入其他模型（如GPT-2）需要如何做呢？

**Comment by zzclynn** [comment]
我们veco的代码是依赖与roberta的，因此我们把roberta的模型代码加到了repo中但没有注册
如果加入gpt2的话可以仿照__init__.py中sbert和veco的做法
