### ISSUE TITLE
language_evaluation link not working

### ISSUE THREAD

**Issue by willxxy** [alibaba/AliceMind#63]
![Screenshot from 2022-11-15 11-50-11](https://user-images.githubusercontent.com/90741489/202012361-aa8207af-dd3d-45ae-a193-082a14e7b4f6.png)
The language_evaluation link does not work. Where can I download the file?
Below is the output after clicking the link. 

![Screenshot from 2022-11-15 11-50-33](https://user-images.githubusercontent.com/90741489/202012358-9e9cd8fc-36dc-450c-9d76-0a80615bbb70.png)

**Comment by willxxy** [comment]
It seems like the package is this repository? (I am not sure but will test out with this.) https://github.com/bckim92/language-evaluation

**Comment by lcl6679292** [comment]
We have fixed the language evaluation download issue, please try downloading again.
