### ISSUE TITLE
Where is UED?

### ISSUE THREAD

**Issue by LegendaryDan** [alibaba/AliceMind#9]
I cannot find UED that was mentioned in the PR article. 

Could you please give the paper link?

Thanks.

**Comment by luofuli** [comment]
Paper: A Unified Pretraining Framework for Passage Ranking and Expansion. Ming Yan, Chenliang Li, Bin Bi, Wei Wang, Songfang Huang. 

Link: https://www.aaai.org/AAAI21Papers/AAAI-9208.YanM.pdf
